"""first migration

Revision ID: 2667f99fcc01
Revises: 
Create Date: 2022-12-07 00:39:31.997036

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2667f99fcc01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_results',
    sa.Column('bdd_feature_uuid', sa.Text(), nullable=False),
    sa.Column('test_uuid', sa.Text(), nullable=True),
    sa.Column('bdd_feature_file_name', sa.Text(), nullable=True),
    sa.Column('test_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('bdd_feature_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('module_results')
    # ### end Alembic commands ###
