"""renaming table

Revision ID: 57d42807cfbb
Revises: 2667f99fcc01
Create Date: 2022-12-08 18:19:05.376892

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '57d42807cfbb'
down_revision = '2667f99fcc01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('module_results')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_results',
    sa.Column('bdd_feature_uuid', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('test_uuid', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bdd_feature_file_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('test_results', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('time_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('time_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('bdd_feature_uuid', name='module_results_pkey')
    )
    # ### end Alembic commands ###
